apiVersion: v1
kind: Service
metadata:
  name: icu-resource-manager
  labels:
    app.kubernetes.io/name: icu-resource-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: icu-resource-manager
  ports:
    - name: http
      port: 80
      targetPort: http
